import {test,expect} from '@playwright/test';
import path from 'node:path';
import fs from 'node:fs/promises';
test.skip(process.env.FRAMES_EXPORT_SYNTHETIC!=='1','仅独立合成处理器服务验证');
const sessions=new WeakMap();
test.beforeEach(async({page})=>{const owned=[];sessions.set(page,owned);page.on('response',response=>{if(response.request().method()==='POST'&&response.url().endsWith('/api/edit-sessions')&&response.ok())owned.push(response.json().then(body=>body.id));});});
test.afterEach(async({page,request})=>{for(const id of await Promise.all(sessions.get(page)||[]))await request.delete(`/api/edit-sessions/${id}`);});
test('统一裁剪与尺寸、最终播放、PNG/ZIP真实下载、框选/保留参数及窄屏',async({page})=>{
  const errors=[];page.on('pageerror',reason=>errors.push(reason.message));
  await page.goto('/');await page.locator('#file').setInputFiles(path.resolve('output/fixtures/自制 动作测试.mp4'));
  await expect(page.locator('#status')).toHaveText('已导入');await page.locator('#end').fill('.25');
  await page.locator('#extract').click();await expect(page.locator('#result-meta')).toContainText('3 帧');
  await page.locator('#organize').click();await page.locator('#tab-export').click();
  await expect(page.locator('#export-empty')).toContainText('先完成');
  await page.locator('#organize').click();
  await page.locator('#edit-grid .frame').first().dragTo(page.locator('#edit-grid .frame').last());
  await expect(page.locator('#edit-meta')).toContainText('未导出');
  await page.locator('#tab-matting').click();await page.locator('#matting-start').click();
  await expect(page.locator('#matting-meta')).toContainText('3 帧已抠');
  await page.locator('#tab-export').click();await expect(page.locator('#export-canvas')).toBeVisible();
  await expect(page.locator('#export-advanced')).not.toHaveAttribute('open');
  await page.locator('#export-fps').fill('0');await page.locator('#export-fps').blur();await expect(page.locator('#export-fps')).toHaveValue('12');
  await page.locator('#export-size').selectOption('half');await expect(page.locator('#export-summary')).toContainText('160 × 90');
  await page.locator('#export-size').selectOption('quarter');await expect(page.locator('#export-summary')).toContainText('80 × 45');
  await page.locator('#export-size').selectOption('eighth');await expect(page.locator('#export-summary')).toContainText('40 × 23');
  await page.locator('#export-size').selectOption('original');
  await expect(page.locator('#export-summary')).toContainText('320 × 180');
  await page.locator('#export-advanced summary').click();
  await page.locator('#export-auto').click();await page.locator('#export-padding').fill('0');await page.locator('#export-padding').blur();
  await expect(page.locator('#export-summary')).toContainText('34 × 40');
  await page.locator('#export-size').selectOption('64');await page.locator('#export-filter').selectOption('pixel');
  await expect.poll(()=>page.locator('#export-canvas').evaluate(canvas=>({width:canvas.width,height:canvas.height,displayWidth:canvas.getBoundingClientRect().width,displayHeight:canvas.getBoundingClientRect().height}))).toEqual({width:64,height:64,displayWidth:64,displayHeight:64});
  await expect(page.locator('#export-zoom-label')).toHaveText('100%');
  const pixels=await page.locator('#export-canvas').evaluate(canvas=>canvas.toDataURL());
  await page.locator('#export-100').click();await page.locator('#export-fit').click();
  expect(await page.locator('#export-canvas').evaluate(canvas=>canvas.toDataURL())).toBe(pixels);
  await page.locator('#export-name').fill('跑步测试');await page.locator('#export-name').blur();
  await expect(page.locator('#export-download')).toBeEnabled();
  const beforePlayback=await page.locator('#export-canvas').evaluate(canvas=>canvas.toDataURL());
  await page.evaluate(()=>{
    window.playbackFlicker=[];
    const ids=['tab-extract','organize','tab-export','export-play','export-download'];
    window.playbackObserver=new MutationObserver(records=>{
      for(const record of records)if(record.oldValue!==record.target.getAttribute('disabled'))window.playbackFlicker.push(record.target.id);
    });
    for(const id of ids)window.playbackObserver.observe(document.getElementById(id),{attributes:true,attributeFilter:['disabled'],attributeOldValue:true});
  });
  await page.route('**/api/export/preview',async route=>{
    const response=await route.fetch();await new Promise(resolve=>setTimeout(resolve,300));await route.fulfill({response});
  });
  await page.locator('#export-fps').fill('2');await page.locator('#export-fps').blur();await page.locator('#export-play').click();
  await expect(page.locator('#export-position')).not.toHaveText('1 / 3');
  await expect.poll(()=>page.locator('#export-canvas').evaluate(canvas=>canvas.toDataURL())).not.toBe(beforePlayback);
  await page.locator('#export-play').click();
  expect(await page.evaluate(()=>{window.playbackObserver.disconnect();return window.playbackFlicker;})).toEqual([]);
  await page.unroute('**/api/export/preview');
  await expect(page.locator('#export-download')).toBeEnabled();
  await fs.mkdir(path.resolve('output/export-acceptance'),{recursive:true});
  let finishPreview;const previewGate=new Promise(resolve=>finishPreview=resolve);let previewHeld=false,downloadStarted=false;
  await page.route('**/api/export/preview',async route=>{const response=await route.fetch();previewHeld=true;await previewGate;await route.fulfill({response});});
  const watchDownload=request=>{if(request.url().endsWith('/api/export/download'))downloadStarted=true;};page.on('request',watchDownload);
  await page.locator('#export-filter').selectOption('smooth');await expect.poll(()=>previewHeld).toBe(true);
  let event=page.waitForEvent('download');await page.locator('#export-download').click();
  try{await expect(page.locator('#tab-extract')).toBeDisabled();expect(downloadStarted).toBe(false);}finally{finishPreview();}
  let file=await event;page.off('request',watchDownload);await page.unroute('**/api/export/preview');
  expect(file.suggestedFilename()).toBe('跑步测试.zip');await file.saveAs(path.resolve('output/export-acceptance/frames.zip'));
  await expect(page.locator('#edit-meta')).not.toContainText('未导出');
  await page.locator('#export-format').selectOption('sheet');await page.locator('#export-columns').fill('2');await page.locator('#export-columns').blur();
  await expect(page.locator('#export-summary')).toContainText('128 × 128');await expect(page.locator('#export-download')).toBeEnabled();
  event=page.waitForEvent('download');await page.locator('#export-download').click();file=await event;
  expect(file.suggestedFilename()).toBe('跑步测试.zip');await file.saveAs(path.resolve('output/export-acceptance/sheet.zip'));
  await page.locator('#export-sheet-view').click();
  await expect.poll(()=>page.locator('#export-canvas').evaluate(canvas=>[canvas.width,canvas.height])).toEqual([128,128]);
  await expect(page.locator('#export-play')).toBeDisabled();await expect(page.locator('#export-position')).toHaveText('整张图集');
  await page.screenshot({path:'output/export-acceptance/sheet-overview.png'});
  await page.locator('#export-sheet-view').click();
  await expect.poll(()=>page.locator('#export-canvas').evaluate(canvas=>canvas.width)).toBe(64);
  for(const viewport of [{width:1440,height:1000},{width:800,height:600},{width:390,height:844}]){
    await page.setViewportSize(viewport);
    expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth&&document.documentElement.scrollHeight<=innerHeight)).toBe(true);
    expect(await page.locator('#export-canvas').evaluate(canvas=>canvas.getBoundingClientRect().width)).toBe(64);
    const r=await page.locator('#export-download').boundingBox();expect(r.x+r.width).toBeLessThanOrEqual(viewport.width);expect(r.y+r.height).toBeLessThanOrEqual(viewport.height);
    await page.screenshot({path:`output/export-acceptance/workspace-${viewport.width}.png`});
  }
  await page.setViewportSize({width:1440,height:1000});await page.locator('#export-box-mode').click();
  await expect(page.locator('#export-preview-title')).toHaveText('框选整组裁剪范围');
  const c=await page.locator('#export-canvas').boundingBox();await page.mouse.move(c.x+c.width*.1,c.y+c.height*.1);await page.mouse.down();await page.mouse.move(c.x+c.width*.8,c.y+c.height*.8,{steps:8});await page.mouse.up();
  await expect(page.locator('#export-crop-warning')).toContainText('截断');
  await page.locator('#export-box-mode').click();await expect(page.locator('#export-preview-title')).toHaveText('输出预览');
  await expect(page.locator('#tab-extract')).toBeEnabled();await page.locator('#tab-extract').click();await page.locator('#tab-export').click();
  await expect(page.locator('#export-name')).toHaveValue('跑步测试');await expect(page.locator('#export-size')).toHaveValue('64');
  let finishNavigationPreview;const navigationGate=new Promise(resolve=>finishNavigationPreview=resolve);let navigationPreviewHeld=false;
  await page.route('**/api/export/preview',async route=>{const response=await route.fetch();navigationPreviewHeld=true;await navigationGate;await route.fulfill({response});});
  await page.locator('#export-filter').selectOption('pixel');await expect.poll(()=>navigationPreviewHeld).toBe(true);
  await expect(page.locator('#tab-extract')).toBeEnabled();await page.locator('#tab-extract').click();
  try{await expect(page.locator('#export-workspace')).toBeVisible();await expect(page.locator('#tab-extract')).toBeDisabled();}finally{finishNavigationPreview();}
  await expect(page.locator('#extract-workspace')).toBeVisible();await page.unroute('**/api/export/preview');
  await page.locator('#tab-export').click();await expect(page.locator('#export-download')).toBeEnabled();
  await page.locator('#export-reset').click();await expect(page.locator('#export-summary')).toContainText('320 × 180');
  await expect(page.locator('#export-advanced')).not.toHaveAttribute('open');
  await page.locator('#export-size').selectOption('512');await expect(page.locator('#export-download')).toBeEnabled();
  await page.setViewportSize({width:800,height:600});await page.locator('#export-100').click();
  expect(await page.locator('#export-canvas').evaluate(canvas=>canvas.getBoundingClientRect().width)).toBe(512);
  expect(await page.locator('#export-stage').evaluate(stage=>stage.scrollHeight>stage.clientHeight)).toBe(true);
  await page.locator('#export-fit').click();
  expect(await page.locator('#export-canvas').evaluate(canvas=>canvas.getBoundingClientRect().width<512)).toBe(true);
  await page.setViewportSize({width:1440,height:1000});
  await page.locator('#export-size').selectOption('custom');await page.locator('#export-width').fill('8192');await page.locator('#export-width').blur();await page.locator('#export-height').fill('8192');await page.locator('#export-height').blur();
  await expect(page.locator('#export-download')).toBeDisabled();
  await page.locator('#export-reset').click();await expect(page.locator('#export-download')).toBeEnabled();
  let release;const gate=new Promise(resolve=>release=resolve);
  await page.route('**/api/export/download',async route=>{await gate;await route.fulfill({status:400,contentType:'application/json',body:'{"detail":"测试导出失败"}'});});
  await page.locator('#export-download').click();
  try{await expect(page.locator('#tab-extract')).toBeDisabled();await expect(page.locator('#organize')).toBeDisabled();await expect(page.locator('#export-size')).toBeDisabled();}finally{release();}
  await expect(page.locator('#export-error')).toHaveText('测试导出失败');await expect(page.locator('#export-download')).toBeEnabled();
  await expect(page.locator('#download,#edit-export,#matting-export')).toHaveCount(0);
  expect(errors).toEqual([]);
});

test('13帧循环复用像素缓存，改文件名/动作帧率不重复生成预览',async({page})=>{
  const errors=[];page.on('pageerror',reason=>errors.push(reason.message));
  await page.goto('/');await page.locator('#file').setInputFiles(path.resolve('output/fixtures/自制 动作测试.mp4'));
  await expect(page.locator('#status')).toHaveText('已导入');await page.locator('#end').fill('1.083333');
  await page.locator('#extract').click();await expect(page.locator('#result-meta')).toContainText('13 帧');
  await page.locator('#organize').click();await page.locator('#tab-matting').click();await page.locator('#matting-start').click();
  await expect(page.locator('#matting-meta')).toContainText('13 帧已抠');await page.locator('#tab-export').click();
  await page.locator('#export-size').selectOption('64');
  await expect.poll(()=>page.locator('#export-canvas').evaluate(canvas=>canvas.width)).toBe(64);
  let requests=0;page.on('request',request=>{if(request.url().endsWith('/api/export/preview'))requests++;});
  await page.evaluate(()=>{
    window.exportChanges=0;
    const position=document.getElementById('export-position');let previous=position.textContent;
    window.exportObserver=new MutationObserver(()=>{const current=position.textContent;if(current!==previous){window.exportChanges++;previous=current;}});
    window.exportObserver.observe(position,{childList:true});
  });
  await page.locator('#export-fps').fill('30');await page.locator('#export-fps').blur();await page.locator('#export-play').click();
  await expect.poll(()=>page.evaluate(()=>window.exportChanges)).toBeGreaterThan(45);
  await page.locator('#export-play').click();
  expect(requests).toBeLessThanOrEqual(13);
  const warmed=requests;await page.locator('#export-name').fill('缓存验证');await page.locator('#export-name').blur();
  await page.locator('#export-fps').fill('12');await page.locator('#export-fps').blur();
  await page.locator('#export-next').click();
  expect(requests).toBe(warmed);expect(errors).toEqual([]);
});
